"""empty message

Revision ID: 6727e2b43794
Revises: 07151a85be61
Create Date: 2017-01-07 02:42:16.151409

"""

# revision identifiers, used by Alembic.
revision = '6727e2b43794'
down_revision = '07151a85be61'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_update_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('club__members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club__members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_update_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='club__members_pkey')
    )
    op.drop_table('club_members')
    # ### end Alembic commands ###
